// src/components/dividers/divider-label.vue
<template>
	<table class="w-full">
		<tbody>
			<tr>
				<template v-for="type in cellTypes" :key="getKey(label, type.name)">
					<td v-if="direction === type.name" :class="`${type.class} w-px whitespace-nowrap`">
						<b>{{ label }}</b>
					</td>
					<td v-else class="m-0 p-0">
						<hr />
					</td>
				</template>
			</tr>
		</tbody>
	</table>
</template>

<script setup>
import { computed } from "vue";
import { toRef } from "vue";

// Props
const props = defineProps({
	label: {
		type: String,
		default: "",
	},
	direction: {
		type: String,
		default: "center",
	},
});

const label = toRef(props, "label");
const direction = toRef(props, "direction");

const cellTypes = [
	{ name: "left", class: "pr-4" },
	{ name: "center", class: "p-4" },
	{ name: "right", class: "pl-4" },
];

function getKey(label, typeName) {
	return typeName + "-" + label.replace(/\s+/g, "-").toLowerCase();
}
</script>

// src/components/dividers/divider-label.jsx
import React from "react";

const cellTypes = [
	{ name: "left", class: "pr-4" },
	{ name: "center", class: "p-4" },
	{ name: "right", class: "pl-4" }
];

function getColumn(label, direction, type) {
	let uniqueKey = type.name + '-' + label.replace(/\s+/g, '-').toLowerCase();

	if (direction === type.name) {
		return <td key={uniqueKey} className={`${type.class} w-px whitespace-nowrap`}>
			<b>{label}</b>
		</td>
	}

	return <td key={uniqueKey} className="m-0 p-0">
		<hr />
	</td>
}

export default function DividerLabel({ label = "", direction = "center" }) {
	return (
		<table className="w-full">
			<tbody>
				<tr>
					{
						cellTypes.map((type) => getColumn(label, direction, type))
					}
				</tr>
			</tbody>
		</table>
	);
}
